name: Security Checks

on:
  workflow_call:
    inputs:
      ref:
        description: GitHub ref to scan.
        required: false
        type: string
        default: ''

jobs:
  poutine-scan:
    name: Poutine Security Scan
    uses: ./.github/workflows/security-poutine-scan-callable.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit

  gitleaks-scan:
    name: Gitleaks Secret Scan
    uses: ./.github/workflows/security-gitleaks-callable.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit

  codeql-analysis:
    name: CodeQL SAST Analysis
    uses: ./.github/workflows/security-codeql-callable.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit

  dependency-review:
    name: Dependency Review
    uses: ./.github/workflows/security-dependency-review-callable.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit
